name: .NET Build and Test database

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x' # Substitua pelo número de versão do .NET SDK que você está usando
        
    - name: Restore Dependencies
      run: dotnet restore src/DoacaoViva.Infrastructure.Database.csproj

    - name: Build Solution
      run: dotnet build src/DoacaoViva.Infrastructure.Database.csproj --configuration Release --no-restore

    - name: Run Unit Tests
      run: dotnet test src/DoacaoViva.Infrastructure.Database.csproj --configuration Release --no-build --verbosity normal
